### ISSUE TITLE
Track changes in a file

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/ngx-monaco#1]
Not yet sure how do bubble up changes in the editor/file. We have a `file` input, maybe we should have a `fileChange` output so you would have 2-way databinding with `[(file)]` or something.

We could also make it a custom form control, but not sure if that would be handy to be honest.

@d3lm @PascalPrecht I would highly appreciate the feedback of you guys :).

**Comment by PascalPrecht** [comment]
@SamVerschueren wow, it's great to see you're working on this! This can be very very helpful for us.

I'm not familiar with monaco's APIs but I agree there should be some event we can hook into to listen for value changes in the editor. This could very much be called `fileChange`. The AceEditor implementation we're using right now over at MachineLabs comes with a `valueChange` event, so it's kind of the same thing, just that it isn't semantically bound to the "file". That's mainly because we used to use the editor for console output as well.

I think it could implement `ControlValueAccessor` as well to become a custom from control, as long as it's not a requirement to have it in a form.
